// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcE8klOjySxZ01vgsBIxNOa79PcoeUOys',
    appId: '1:261527270397:web:e1c0d0df41e54824b49f94',
    messagingSenderId: '261527270397',
    projectId: 'db-iot-c500c',
    authDomain: 'db-iot-c500c.firebaseapp.com',
    databaseURL: 'https://db-iot-c500c-default-rtdb.firebaseio.com',
    storageBucket: 'db-iot-c500c.firebasestorage.app',
    measurementId: 'G-SVD6HBDP34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATyB_guc64J3q1lY81Skyz5tKFjAt4MVc',
    appId: '1:261527270397:android:cc9ba67fdb790f54b49f94',
    messagingSenderId: '261527270397',
    projectId: 'db-iot-c500c',
    databaseURL: 'https://db-iot-c500c-default-rtdb.firebaseio.com',
    storageBucket: 'db-iot-c500c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSqHtxYemhl5PQ5p9NZSnftZeYM9Mo3ak',
    appId: '1:261527270397:ios:36feb599b8efe6d3b49f94',
    messagingSenderId: '261527270397',
    projectId: 'db-iot-c500c',
    databaseURL: 'https://db-iot-c500c-default-rtdb.firebaseio.com',
    storageBucket: 'db-iot-c500c.firebasestorage.app',
    iosBundleId: 'com.example.appIotDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSqHtxYemhl5PQ5p9NZSnftZeYM9Mo3ak',
    appId: '1:261527270397:ios:36feb599b8efe6d3b49f94',
    messagingSenderId: '261527270397',
    projectId: 'db-iot-c500c',
    databaseURL: 'https://db-iot-c500c-default-rtdb.firebaseio.com',
    storageBucket: 'db-iot-c500c.firebasestorage.app',
    iosBundleId: 'com.example.appIotDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcE8klOjySxZ01vgsBIxNOa79PcoeUOys',
    appId: '1:261527270397:web:f6c35d9dbe00751bb49f94',
    messagingSenderId: '261527270397',
    projectId: 'db-iot-c500c',
    authDomain: 'db-iot-c500c.firebaseapp.com',
    databaseURL: 'https://db-iot-c500c-default-rtdb.firebaseio.com',
    storageBucket: 'db-iot-c500c.firebasestorage.app',
    measurementId: 'G-V44TYMTK52',
  );
}
